# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python35:
      python.version: '3.7'
    Python36:
      python.version: '3.8'
    Python37:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python setup.py build install
  displayName: 'build'

- script: |
    python module_tests.py
  displayName: 'test'